"""Assemble proxy.asm and turn the COFF object into hifps's proxy_code.lua (and a blob for the test harness).

The object has one section with code and data. Every DIR32 relocation gets its symbol's section
offset added here, so at run time hifps only adds the base of its copy to each listed offset.
"""
import struct, subprocess, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
VC = r'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat'
SYMS = ['D_PENDING', 'D_PBYTES', 'D_STRIDE', 'D_PDEV', 'D_BUF', 'D_BUFSIZE', 'S_SKIPPED', 'S_MERGED',
        'S_BATCHES', 'F_BATCH', 'F_DEDUPE', 'F_REC', 'ORIG', 'VT_RTTI', 'VTABLE', 'THUNK_TABLE',
        'VALID_START', 'VALID_END', 'FLUSH']
NSLOTS = 128


def assemble():
    r = subprocess.run(f'"{VC}" >nul 2>&1 && cd /d "{HERE}" && ml /nologo /c /coff proxy.asm',
                       shell=True, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stdout + r.stderr)


def parse(path):
    d = open(path, 'rb').read()
    machine, nsec, _, symptr, nsym, opt, _ = struct.unpack_from('<HHIIIHH', d, 0)
    assert machine == 0x14C
    secs = []
    for i in range(nsec):
        o = 20 + opt + 40 * i
        name = d[o:o + 8].rstrip(b'\0').decode()
        vsize, va, rsize, rptr, relptr, _, nrel, _, ch = struct.unpack_from('<IIIIIIHHI', d, o + 8)
        secs.append(dict(name=name, rsize=rsize, rptr=rptr, relptr=relptr, nrel=nrel))
    strtab = symptr + 18 * nsym
    syms, i = [], 0
    while i < nsym:
        o = symptr + 18 * i
        raw = d[o:o + 8]
        if raw[:4] == b'\0\0\0\0':
            off = struct.unpack_from('<I', raw, 4)[0]
            name = d[strtab + off:d.index(b'\0', strtab + off)].decode()
        else:
            name = raw.rstrip(b'\0').decode()
        value, secno, typ, cls, naux = struct.unpack_from('<IhHBB', d, o + 8)
        syms.append((name, value, secno))
        syms.extend([None] * naux)
        i += 1 + naux
    code = [s for s in secs if s['name'].startswith('.text')]
    assert len(code) == 1, secs
    sec = code[0]
    secno = secs.index(sec) + 1
    data = bytearray(d[sec['rptr']:sec['rptr'] + sec['rsize']])
    relocs = []
    for k in range(sec['nrel']):
        va, si, typ = struct.unpack_from('<IIH', d, sec['relptr'] + 10 * k)
        assert typ == 6, ('unexpected relocation type', typ)       # IMAGE_REL_I386_DIR32
        name, value, sn = syms[si]
        assert sn == secno, ('relocation outside the section', name)
        struct.pack_into('<I', data, va, struct.unpack_from('<I', data, va)[0] + value)
        relocs.append(va)
    pub = {n: v for (n, v, sn) in (s for s in syms if s) if sn == secno and n in SYMS}
    missing = set(SYMS) - set(pub)
    assert not missing, missing
    return bytes(data), sorted(relocs), pub


def main():
    assemble()
    code, relocs, pub = parse(os.path.join(HERE, 'proxy.obj'))
    # thunk table sanity: every non-zero entry is a relocated pointer into the code
    tt = pub['THUNK_TABLE']
    slots = [struct.unpack_from('<I', code, tt + 4 * i)[0] for i in range(NSLOTS)]
    hooked = [i for i, v in enumerate(slots) if v]
    for i in hooked:
        assert tt + 4 * i in relocs and 0 < slots[i] < len(code), i
    print('code %d bytes, %d relocations, %d hooked slots: %s' % (len(code), len(relocs), len(hooked), hooked))

    out = os.path.join(os.path.dirname(HERE), 'proxy_code.lua')   # next to hifps.lua
    with open(out, 'w', newline='\n') as f:
        f.write('-- Generated by proxy/build.py from proxy/proxy.asm; do not edit.\n')
        f.write('return {\n')
        f.write('    size = %d,\n' % len(code))
        f.write('    sym = { %s },\n' % ', '.join('%s = 0x%X' % (n, pub[n]) for n in SYMS))
        f.write('    relocs = {\n')
        for i in range(0, len(relocs), 12):
            f.write('        %s,\n' % ', '.join('0x%X' % r for r in relocs[i:i + 12]))
        f.write('    },\n')
        f.write('    hex = table.concat({\n')
        h = code.hex().upper()
        for i in range(0, len(h), 128):
            f.write("        '%s',\n" % h[i:i + 128])
        f.write('    }),\n')
        f.write('};\n')
    with open(os.path.join(HERE, 'proxy.blob'), 'wb') as f:
        f.write(struct.pack('<III', len(code), len(relocs), len(SYMS)))
        f.write(struct.pack('<%dI' % len(relocs), *relocs))
        f.write(struct.pack('<%dI' % len(SYMS), *[pub[n] for n in SYMS]))
        f.write(code)
    print('wrote', out)


if __name__ == '__main__':
    main()
